//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadRestaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoVenta
    {
        public long id { get; set; }
        public long idVenta { get; set; }
        public int idMetodoPago { get; set; }
        public decimal monto { get; set; }
        public string usuarioRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public short estado { get; set; }
    
        public virtual MetodoPago MetodoPago { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
